### ISSUE TITLE
Commit information absent on Coveralls

### ISSUE THREAD

**Issue by kshyatt** [timholy/CoverageBase.jl#5]
For the official JuliaLang repository, we don't get the committer of the latest commit nor the commit message. Yet when I run CoverageBase on `julia.mit.edu` or my OSX machine, everything works properly. Is something up with the buildbot?

**Comment by staticfloat** [comment]
This is almost certainly something to do with the buildbot.  The relevant invocation of `CoverageBase` is found in [this file](https://github.com/staticfloat/julia-buildbot/blob/master/master/coverage.py) on a different repository, but we can hash out the issues here.

As you can see [on these lines](https://github.com/staticfloat/julia-buildbot/blob/386912661ac47fc5efb6eae0f13700a8da32e323/master/coverage.py#L30-L45), I'm manually recreating the git information and sending it along to Coveralls.  The information I'm sending gets printed out so that we can take a look at it and make sure its reasonable, however because the MIT OpenStack cloud is down right now, we can't inspect the most recent logs.

**Comment by staticfloat** [comment]
I'm going to go ahead and close this now, since we figured out what the issue was.  Apparently, you need to provide both `Author {Name,Email}` and `Committer {Name,Email}` to get Coveralls to listen to you about anything git-related!  Relevant commit [here](https://github.com/staticfloat/julia-buildbot/commit/7fd5fbe4f2bd13a13877759c4bc532a1733ce4e0).

**Comment by timholy** [comment]
Nice!
